// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cosmossdkgridnode/gridnode/gridnode.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_DelegatedAmount_FullMethodName = "/cosmossdkgridnode.gridnode.Query/DelegatedAmount"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// DelegatedAmount queries the amount delegated by a specific account.
	DelegatedAmount(ctx context.Context, in *QueryDelegatedAmountRequest, opts ...grpc.CallOption) (*QueryDelegatedAmountResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) DelegatedAmount(ctx context.Context, in *QueryDelegatedAmountRequest, opts ...grpc.CallOption) (*QueryDelegatedAmountResponse, error) {
	out := new(QueryDelegatedAmountResponse)
	err := c.cc.Invoke(ctx, Query_DelegatedAmount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// DelegatedAmount queries the amount delegated by a specific account.
	DelegatedAmount(context.Context, *QueryDelegatedAmountRequest) (*QueryDelegatedAmountResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) DelegatedAmount(context.Context, *QueryDelegatedAmountRequest) (*QueryDelegatedAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegatedAmount not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_DelegatedAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDelegatedAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DelegatedAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DelegatedAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DelegatedAmount(ctx, req.(*QueryDelegatedAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cosmossdkgridnode.gridnode.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DelegatedAmount",
			Handler:    _Query_DelegatedAmount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmossdkgridnode/gridnode/gridnode.proto",
}

const (
	GridnodeMsg_DelegateTokens_FullMethodName = "/cosmossdkgridnode.gridnode.GridnodeMsg/DelegateTokens"
)

// GridnodeMsgClient is the client API for GridnodeMsg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GridnodeMsgClient interface {
	DelegateTokens(ctx context.Context, in *MsgDelegateTokens, opts ...grpc.CallOption) (*MsgDelegateTokensResponse, error)
}

type gridnodeMsgClient struct {
	cc grpc.ClientConnInterface
}

func NewGridnodeMsgClient(cc grpc.ClientConnInterface) GridnodeMsgClient {
	return &gridnodeMsgClient{cc}
}

func (c *gridnodeMsgClient) DelegateTokens(ctx context.Context, in *MsgDelegateTokens, opts ...grpc.CallOption) (*MsgDelegateTokensResponse, error) {
	out := new(MsgDelegateTokensResponse)
	err := c.cc.Invoke(ctx, GridnodeMsg_DelegateTokens_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GridnodeMsgServer is the server API for GridnodeMsg service.
// All implementations must embed UnimplementedGridnodeMsgServer
// for forward compatibility
type GridnodeMsgServer interface {
	DelegateTokens(context.Context, *MsgDelegateTokens) (*MsgDelegateTokensResponse, error)
	mustEmbedUnimplementedGridnodeMsgServer()
}

// UnimplementedGridnodeMsgServer must be embedded to have forward compatible implementations.
type UnimplementedGridnodeMsgServer struct {
}

func (UnimplementedGridnodeMsgServer) DelegateTokens(context.Context, *MsgDelegateTokens) (*MsgDelegateTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegateTokens not implemented")
}
func (UnimplementedGridnodeMsgServer) mustEmbedUnimplementedGridnodeMsgServer() {}

// UnsafeGridnodeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GridnodeMsgServer will
// result in compilation errors.
type UnsafeGridnodeMsgServer interface {
	mustEmbedUnimplementedGridnodeMsgServer()
}

func RegisterGridnodeMsgServer(s grpc.ServiceRegistrar, srv GridnodeMsgServer) {
	s.RegisterService(&GridnodeMsg_ServiceDesc, srv)
}

func _GridnodeMsg_DelegateTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDelegateTokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridnodeMsgServer).DelegateTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GridnodeMsg_DelegateTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridnodeMsgServer).DelegateTokens(ctx, req.(*MsgDelegateTokens))
	}
	return interceptor(ctx, in, info, handler)
}

// GridnodeMsg_ServiceDesc is the grpc.ServiceDesc for GridnodeMsg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GridnodeMsg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cosmossdkgridnode.gridnode.GridnodeMsg",
	HandlerType: (*GridnodeMsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DelegateTokens",
			Handler:    _GridnodeMsg_DelegateTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmossdkgridnode/gridnode/gridnode.proto",
}
